-- Generated By protoc-gen-lua do no edit
local protobuf = require "protobuf/protobuf"
local VO_PB = require("protocols/VO_pb")
local m_table = {}
setmetatable(m_table,{__index = _G})
local _ENV = m_table

local localTable = {}
localTable.REQUESTTYPE = protobuf.EnumDescriptor()
localTable.REQUESTTYPE_REQ_HEARTBEAT_ENUM = protobuf.EnumValueDescriptor()
localTable.REQUESTTYPE_REQ_LOGIN_ENUM = protobuf.EnumValueDescriptor()
localTable.REQUESTTYPE_REQ_CREATEPLAYER_ENUM = protobuf.EnumValueDescriptor()
localTable.REQUESTTYPE_REQ_BATTLE_ENUM = protobuf.EnumValueDescriptor()
C2GREQUEST = protobuf.Descriptor()
localTable.C2GREQUEST_MSGTYPE_FIELD = protobuf.FieldDescriptor()
localTable.C2GREQUEST_MSGBODY_FIELD = protobuf.FieldDescriptor()
localTable.C2GREQUEST_SESSIONID_FIELD = protobuf.FieldDescriptor()
localTable.C2GREQUEST_MSGCOUNT_FIELD = protobuf.FieldDescriptor()
REQ_HEARTBEATMSG = protobuf.Descriptor()
localTable.REQ_HEARTBEATMSG_MSGTYPE_FIELD = protobuf.FieldDescriptor()
REQ_LOGINMSG = protobuf.Descriptor()
localTable.REQ_LOGINMSG_MSGTYPE_FIELD = protobuf.FieldDescriptor()
localTable.REQ_LOGINMSG_SECURECODE_FIELD = protobuf.FieldDescriptor()
localTable.REQ_LOGINMSG_VERSION_FIELD = protobuf.FieldDescriptor()
REQ_CREATEPLAYERMSG = protobuf.Descriptor()
localTable.REQ_CREATEPLAYERMSG_MSGTYPE_FIELD = protobuf.FieldDescriptor()
localTable.REQ_CREATEPLAYERMSG_SECURECODE_FIELD = protobuf.FieldDescriptor()
localTable.REQ_CREATEPLAYERMSG_SEX_FIELD = protobuf.FieldDescriptor()
localTable.REQ_CREATEPLAYERMSG_PLAYERNAME_FIELD = protobuf.FieldDescriptor()
REQ_BATTLEMSG = protobuf.Descriptor()
localTable.REQ_BATTLEMSG_MSGTYPE_FIELD = protobuf.FieldDescriptor()
localTable.REQ_BATTLEMSG_BTTYPE_FIELD = protobuf.FieldDescriptor()
localTable.REQ_BATTLEMSG_LEVELID_FIELD = protobuf.FieldDescriptor()
localTable.REQ_BATTLEMSG_BTINFOS_FIELD = protobuf.FieldDescriptor()

Req_Heartbeat = 1
Req_Login = 2
Req_CreatePlayer = 3
Req_Battle = 4

localTable.REQUESTTYPE_REQ_HEARTBEAT_ENUM.name = "Req_Heartbeat"
localTable.REQUESTTYPE_REQ_HEARTBEAT_ENUM.index = 0
localTable.REQUESTTYPE_REQ_HEARTBEAT_ENUM.number = 1
localTable.REQUESTTYPE_REQ_LOGIN_ENUM.name = "Req_Login"
localTable.REQUESTTYPE_REQ_LOGIN_ENUM.index = 1
localTable.REQUESTTYPE_REQ_LOGIN_ENUM.number = 2
localTable.REQUESTTYPE_REQ_CREATEPLAYER_ENUM.name = "Req_CreatePlayer"
localTable.REQUESTTYPE_REQ_CREATEPLAYER_ENUM.index = 2
localTable.REQUESTTYPE_REQ_CREATEPLAYER_ENUM.number = 3
localTable.REQUESTTYPE_REQ_BATTLE_ENUM.name = "Req_Battle"
localTable.REQUESTTYPE_REQ_BATTLE_ENUM.index = 3
localTable.REQUESTTYPE_REQ_BATTLE_ENUM.number = 4
localTable.REQUESTTYPE.name = "RequestType"
localTable.REQUESTTYPE.full_name = ".C2GRequestMsgProto.RequestType"
localTable.REQUESTTYPE.values = {localTable.REQUESTTYPE_REQ_HEARTBEAT_ENUM,localTable.REQUESTTYPE_REQ_LOGIN_ENUM,localTable.REQUESTTYPE_REQ_CREATEPLAYER_ENUM,localTable.REQUESTTYPE_REQ_BATTLE_ENUM}
localTable.C2GREQUEST_MSGTYPE_FIELD.name = "msgType"
localTable.C2GREQUEST_MSGTYPE_FIELD.full_name = ".C2GRequestMsgProto.C2GRequest.msgType"
localTable.C2GREQUEST_MSGTYPE_FIELD.number = 1
localTable.C2GREQUEST_MSGTYPE_FIELD.index = 0
localTable.C2GREQUEST_MSGTYPE_FIELD.label = 2
localTable.C2GREQUEST_MSGTYPE_FIELD.has_default_value = false
localTable.C2GREQUEST_MSGTYPE_FIELD.default_value = nil
localTable.C2GREQUEST_MSGTYPE_FIELD.enum_type = localTable.REQUESTTYPE
localTable.C2GREQUEST_MSGTYPE_FIELD.type = 14
localTable.C2GREQUEST_MSGTYPE_FIELD.cpp_type = 8

localTable.C2GREQUEST_MSGBODY_FIELD.name = "msgBody"
localTable.C2GREQUEST_MSGBODY_FIELD.full_name = ".C2GRequestMsgProto.C2GRequest.msgBody"
localTable.C2GREQUEST_MSGBODY_FIELD.number = 2
localTable.C2GREQUEST_MSGBODY_FIELD.index = 1
localTable.C2GREQUEST_MSGBODY_FIELD.label = 2
localTable.C2GREQUEST_MSGBODY_FIELD.has_default_value = false
localTable.C2GREQUEST_MSGBODY_FIELD.default_value = ""
localTable.C2GREQUEST_MSGBODY_FIELD.type = 12
localTable.C2GREQUEST_MSGBODY_FIELD.cpp_type = 9

localTable.C2GREQUEST_SESSIONID_FIELD.name = "sessionId"
localTable.C2GREQUEST_SESSIONID_FIELD.full_name = ".C2GRequestMsgProto.C2GRequest.sessionId"
localTable.C2GREQUEST_SESSIONID_FIELD.number = 3
localTable.C2GREQUEST_SESSIONID_FIELD.index = 2
localTable.C2GREQUEST_SESSIONID_FIELD.label = 1
localTable.C2GREQUEST_SESSIONID_FIELD.has_default_value = false
localTable.C2GREQUEST_SESSIONID_FIELD.default_value = ""
localTable.C2GREQUEST_SESSIONID_FIELD.type = 9
localTable.C2GREQUEST_SESSIONID_FIELD.cpp_type = 9

localTable.C2GREQUEST_MSGCOUNT_FIELD.name = "msgCount"
localTable.C2GREQUEST_MSGCOUNT_FIELD.full_name = ".C2GRequestMsgProto.C2GRequest.msgCount"
localTable.C2GREQUEST_MSGCOUNT_FIELD.number = 4
localTable.C2GREQUEST_MSGCOUNT_FIELD.index = 3
localTable.C2GREQUEST_MSGCOUNT_FIELD.label = 1
localTable.C2GREQUEST_MSGCOUNT_FIELD.has_default_value = false
localTable.C2GREQUEST_MSGCOUNT_FIELD.default_value = 0
localTable.C2GREQUEST_MSGCOUNT_FIELD.type = 5
localTable.C2GREQUEST_MSGCOUNT_FIELD.cpp_type = 1

C2GREQUEST.name = "C2GRequest"
C2GREQUEST.full_name = ".C2GRequestMsgProto.C2GRequest"
C2GREQUEST.nested_types = {}
C2GREQUEST.enum_types = {}
C2GREQUEST.fields = {localTable.C2GREQUEST_MSGTYPE_FIELD, localTable.C2GREQUEST_MSGBODY_FIELD, localTable.C2GREQUEST_SESSIONID_FIELD, localTable.C2GREQUEST_MSGCOUNT_FIELD}
C2GREQUEST.is_extendable = false
C2GREQUEST.extensions = {}
localTable.REQ_HEARTBEATMSG_MSGTYPE_FIELD.name = "msgType"
localTable.REQ_HEARTBEATMSG_MSGTYPE_FIELD.full_name = ".C2GRequestMsgProto.Req_HeartbeatMsg.msgType"
localTable.REQ_HEARTBEATMSG_MSGTYPE_FIELD.number = 1
localTable.REQ_HEARTBEATMSG_MSGTYPE_FIELD.index = 0
localTable.REQ_HEARTBEATMSG_MSGTYPE_FIELD.label = 1
localTable.REQ_HEARTBEATMSG_MSGTYPE_FIELD.has_default_value = true
localTable.REQ_HEARTBEATMSG_MSGTYPE_FIELD.default_value = Req_Heartbeat
localTable.REQ_HEARTBEATMSG_MSGTYPE_FIELD.enum_type = localTable.REQUESTTYPE
localTable.REQ_HEARTBEATMSG_MSGTYPE_FIELD.type = 14
localTable.REQ_HEARTBEATMSG_MSGTYPE_FIELD.cpp_type = 8

REQ_HEARTBEATMSG.name = "Req_HeartbeatMsg"
REQ_HEARTBEATMSG.full_name = ".C2GRequestMsgProto.Req_HeartbeatMsg"
REQ_HEARTBEATMSG.nested_types = {}
REQ_HEARTBEATMSG.enum_types = {}
REQ_HEARTBEATMSG.fields = {localTable.REQ_HEARTBEATMSG_MSGTYPE_FIELD}
REQ_HEARTBEATMSG.is_extendable = false
REQ_HEARTBEATMSG.extensions = {}
localTable.REQ_LOGINMSG_MSGTYPE_FIELD.name = "msgType"
localTable.REQ_LOGINMSG_MSGTYPE_FIELD.full_name = ".C2GRequestMsgProto.Req_LoginMsg.msgType"
localTable.REQ_LOGINMSG_MSGTYPE_FIELD.number = 1
localTable.REQ_LOGINMSG_MSGTYPE_FIELD.index = 0
localTable.REQ_LOGINMSG_MSGTYPE_FIELD.label = 1
localTable.REQ_LOGINMSG_MSGTYPE_FIELD.has_default_value = true
localTable.REQ_LOGINMSG_MSGTYPE_FIELD.default_value = Req_Login
localTable.REQ_LOGINMSG_MSGTYPE_FIELD.enum_type = localTable.REQUESTTYPE
localTable.REQ_LOGINMSG_MSGTYPE_FIELD.type = 14
localTable.REQ_LOGINMSG_MSGTYPE_FIELD.cpp_type = 8

localTable.REQ_LOGINMSG_SECURECODE_FIELD.name = "secureCode"
localTable.REQ_LOGINMSG_SECURECODE_FIELD.full_name = ".C2GRequestMsgProto.Req_LoginMsg.secureCode"
localTable.REQ_LOGINMSG_SECURECODE_FIELD.number = 2
localTable.REQ_LOGINMSG_SECURECODE_FIELD.index = 1
localTable.REQ_LOGINMSG_SECURECODE_FIELD.label = 1
localTable.REQ_LOGINMSG_SECURECODE_FIELD.has_default_value = false
localTable.REQ_LOGINMSG_SECURECODE_FIELD.default_value = ""
localTable.REQ_LOGINMSG_SECURECODE_FIELD.type = 9
localTable.REQ_LOGINMSG_SECURECODE_FIELD.cpp_type = 9

localTable.REQ_LOGINMSG_VERSION_FIELD.name = "version"
localTable.REQ_LOGINMSG_VERSION_FIELD.full_name = ".C2GRequestMsgProto.Req_LoginMsg.version"
localTable.REQ_LOGINMSG_VERSION_FIELD.number = 3
localTable.REQ_LOGINMSG_VERSION_FIELD.index = 2
localTable.REQ_LOGINMSG_VERSION_FIELD.label = 1
localTable.REQ_LOGINMSG_VERSION_FIELD.has_default_value = false
localTable.REQ_LOGINMSG_VERSION_FIELD.default_value = ""
localTable.REQ_LOGINMSG_VERSION_FIELD.type = 9
localTable.REQ_LOGINMSG_VERSION_FIELD.cpp_type = 9

REQ_LOGINMSG.name = "Req_LoginMsg"
REQ_LOGINMSG.full_name = ".C2GRequestMsgProto.Req_LoginMsg"
REQ_LOGINMSG.nested_types = {}
REQ_LOGINMSG.enum_types = {}
REQ_LOGINMSG.fields = {localTable.REQ_LOGINMSG_MSGTYPE_FIELD, localTable.REQ_LOGINMSG_SECURECODE_FIELD, localTable.REQ_LOGINMSG_VERSION_FIELD}
REQ_LOGINMSG.is_extendable = false
REQ_LOGINMSG.extensions = {}
localTable.REQ_CREATEPLAYERMSG_MSGTYPE_FIELD.name = "msgType"
localTable.REQ_CREATEPLAYERMSG_MSGTYPE_FIELD.full_name = ".C2GRequestMsgProto.Req_CreatePlayerMsg.msgType"
localTable.REQ_CREATEPLAYERMSG_MSGTYPE_FIELD.number = 1
localTable.REQ_CREATEPLAYERMSG_MSGTYPE_FIELD.index = 0
localTable.REQ_CREATEPLAYERMSG_MSGTYPE_FIELD.label = 1
localTable.REQ_CREATEPLAYERMSG_MSGTYPE_FIELD.has_default_value = true
localTable.REQ_CREATEPLAYERMSG_MSGTYPE_FIELD.default_value = Req_CreatePlayer
localTable.REQ_CREATEPLAYERMSG_MSGTYPE_FIELD.enum_type = localTable.REQUESTTYPE
localTable.REQ_CREATEPLAYERMSG_MSGTYPE_FIELD.type = 14
localTable.REQ_CREATEPLAYERMSG_MSGTYPE_FIELD.cpp_type = 8

localTable.REQ_CREATEPLAYERMSG_SECURECODE_FIELD.name = "secureCode"
localTable.REQ_CREATEPLAYERMSG_SECURECODE_FIELD.full_name = ".C2GRequestMsgProto.Req_CreatePlayerMsg.secureCode"
localTable.REQ_CREATEPLAYERMSG_SECURECODE_FIELD.number = 2
localTable.REQ_CREATEPLAYERMSG_SECURECODE_FIELD.index = 1
localTable.REQ_CREATEPLAYERMSG_SECURECODE_FIELD.label = 1
localTable.REQ_CREATEPLAYERMSG_SECURECODE_FIELD.has_default_value = false
localTable.REQ_CREATEPLAYERMSG_SECURECODE_FIELD.default_value = ""
localTable.REQ_CREATEPLAYERMSG_SECURECODE_FIELD.type = 9
localTable.REQ_CREATEPLAYERMSG_SECURECODE_FIELD.cpp_type = 9

localTable.REQ_CREATEPLAYERMSG_SEX_FIELD.name = "sex"
localTable.REQ_CREATEPLAYERMSG_SEX_FIELD.full_name = ".C2GRequestMsgProto.Req_CreatePlayerMsg.sex"
localTable.REQ_CREATEPLAYERMSG_SEX_FIELD.number = 3
localTable.REQ_CREATEPLAYERMSG_SEX_FIELD.index = 2
localTable.REQ_CREATEPLAYERMSG_SEX_FIELD.label = 1
localTable.REQ_CREATEPLAYERMSG_SEX_FIELD.has_default_value = false
localTable.REQ_CREATEPLAYERMSG_SEX_FIELD.default_value = 0
localTable.REQ_CREATEPLAYERMSG_SEX_FIELD.type = 5
localTable.REQ_CREATEPLAYERMSG_SEX_FIELD.cpp_type = 1

localTable.REQ_CREATEPLAYERMSG_PLAYERNAME_FIELD.name = "playerName"
localTable.REQ_CREATEPLAYERMSG_PLAYERNAME_FIELD.full_name = ".C2GRequestMsgProto.Req_CreatePlayerMsg.playerName"
localTable.REQ_CREATEPLAYERMSG_PLAYERNAME_FIELD.number = 4
localTable.REQ_CREATEPLAYERMSG_PLAYERNAME_FIELD.index = 3
localTable.REQ_CREATEPLAYERMSG_PLAYERNAME_FIELD.label = 1
localTable.REQ_CREATEPLAYERMSG_PLAYERNAME_FIELD.has_default_value = false
localTable.REQ_CREATEPLAYERMSG_PLAYERNAME_FIELD.default_value = ""
localTable.REQ_CREATEPLAYERMSG_PLAYERNAME_FIELD.type = 9
localTable.REQ_CREATEPLAYERMSG_PLAYERNAME_FIELD.cpp_type = 9

REQ_CREATEPLAYERMSG.name = "Req_CreatePlayerMsg"
REQ_CREATEPLAYERMSG.full_name = ".C2GRequestMsgProto.Req_CreatePlayerMsg"
REQ_CREATEPLAYERMSG.nested_types = {}
REQ_CREATEPLAYERMSG.enum_types = {}
REQ_CREATEPLAYERMSG.fields = {localTable.REQ_CREATEPLAYERMSG_MSGTYPE_FIELD, localTable.REQ_CREATEPLAYERMSG_SECURECODE_FIELD, localTable.REQ_CREATEPLAYERMSG_SEX_FIELD, localTable.REQ_CREATEPLAYERMSG_PLAYERNAME_FIELD}
REQ_CREATEPLAYERMSG.is_extendable = false
REQ_CREATEPLAYERMSG.extensions = {}
localTable.REQ_BATTLEMSG_MSGTYPE_FIELD.name = "msgType"
localTable.REQ_BATTLEMSG_MSGTYPE_FIELD.full_name = ".C2GRequestMsgProto.Req_BattleMsg.msgType"
localTable.REQ_BATTLEMSG_MSGTYPE_FIELD.number = 1
localTable.REQ_BATTLEMSG_MSGTYPE_FIELD.index = 0
localTable.REQ_BATTLEMSG_MSGTYPE_FIELD.label = 1
localTable.REQ_BATTLEMSG_MSGTYPE_FIELD.has_default_value = true
localTable.REQ_BATTLEMSG_MSGTYPE_FIELD.default_value = Req_Battle
localTable.REQ_BATTLEMSG_MSGTYPE_FIELD.enum_type = localTable.REQUESTTYPE
localTable.REQ_BATTLEMSG_MSGTYPE_FIELD.type = 14
localTable.REQ_BATTLEMSG_MSGTYPE_FIELD.cpp_type = 8

localTable.REQ_BATTLEMSG_BTTYPE_FIELD.name = "btType"
localTable.REQ_BATTLEMSG_BTTYPE_FIELD.full_name = ".C2GRequestMsgProto.Req_BattleMsg.btType"
localTable.REQ_BATTLEMSG_BTTYPE_FIELD.number = 2
localTable.REQ_BATTLEMSG_BTTYPE_FIELD.index = 1
localTable.REQ_BATTLEMSG_BTTYPE_FIELD.label = 1
localTable.REQ_BATTLEMSG_BTTYPE_FIELD.has_default_value = false
localTable.REQ_BATTLEMSG_BTTYPE_FIELD.default_value = 0
localTable.REQ_BATTLEMSG_BTTYPE_FIELD.type = 5
localTable.REQ_BATTLEMSG_BTTYPE_FIELD.cpp_type = 1

localTable.REQ_BATTLEMSG_LEVELID_FIELD.name = "levelId"
localTable.REQ_BATTLEMSG_LEVELID_FIELD.full_name = ".C2GRequestMsgProto.Req_BattleMsg.levelId"
localTable.REQ_BATTLEMSG_LEVELID_FIELD.number = 3
localTable.REQ_BATTLEMSG_LEVELID_FIELD.index = 2
localTable.REQ_BATTLEMSG_LEVELID_FIELD.label = 1
localTable.REQ_BATTLEMSG_LEVELID_FIELD.has_default_value = false
localTable.REQ_BATTLEMSG_LEVELID_FIELD.default_value = 0
localTable.REQ_BATTLEMSG_LEVELID_FIELD.type = 5
localTable.REQ_BATTLEMSG_LEVELID_FIELD.cpp_type = 1

localTable.REQ_BATTLEMSG_BTINFOS_FIELD.name = "btInfos"
localTable.REQ_BATTLEMSG_BTINFOS_FIELD.full_name = ".C2GRequestMsgProto.Req_BattleMsg.btInfos"
localTable.REQ_BATTLEMSG_BTINFOS_FIELD.number = 4
localTable.REQ_BATTLEMSG_BTINFOS_FIELD.index = 3
localTable.REQ_BATTLEMSG_BTINFOS_FIELD.label = 3
localTable.REQ_BATTLEMSG_BTINFOS_FIELD.has_default_value = false
localTable.REQ_BATTLEMSG_BTINFOS_FIELD.default_value = {}
localTable.REQ_BATTLEMSG_BTINFOS_FIELD.message_type = VO_PB.BATTLEINFOVO
localTable.REQ_BATTLEMSG_BTINFOS_FIELD.type = 11
localTable.REQ_BATTLEMSG_BTINFOS_FIELD.cpp_type = 10

REQ_BATTLEMSG.name = "Req_BattleMsg"
REQ_BATTLEMSG.full_name = ".C2GRequestMsgProto.Req_BattleMsg"
REQ_BATTLEMSG.nested_types = {}
REQ_BATTLEMSG.enum_types = {}
REQ_BATTLEMSG.fields = {localTable.REQ_BATTLEMSG_MSGTYPE_FIELD, localTable.REQ_BATTLEMSG_BTTYPE_FIELD, localTable.REQ_BATTLEMSG_LEVELID_FIELD, localTable.REQ_BATTLEMSG_BTINFOS_FIELD}
REQ_BATTLEMSG.is_extendable = false
REQ_BATTLEMSG.extensions = {}

-- msgType, 
Req_HeartbeatMsg = protobuf.Message(REQ_HEARTBEATMSG)

-- msgType, btType, levelId, btInfos, 
Req_BattleMsg = protobuf.Message(REQ_BATTLEMSG)

-- msgType, msgBody, sessionId, msgCount, 
C2GRequest = protobuf.Message(C2GREQUEST)

-- msgType, secureCode, sex, playerName, 
Req_CreatePlayerMsg = protobuf.Message(REQ_CREATEPLAYERMSG)

-- msgType, secureCode, version, 
Req_LoginMsg = protobuf.Message(REQ_LOGINMSG)


return m_table