-- Generated By protoc-gen-lua do no edit
local protobuf = require "protobuf/protobuf"
local VO_PB = require("protocols/VO_pb")
local m_table = {}
setmetatable(m_table,{__index = _G})
local _ENV = m_table

local localTable = {}
localTable.RESPONSETYPE = protobuf.EnumDescriptor()
localTable.RESPONSETYPE_RES_HEARTBEAT_ENUM = protobuf.EnumValueDescriptor()
localTable.RESPONSETYPE_RES_LOGIN_ENUM = protobuf.EnumValueDescriptor()
localTable.RESPONSETYPE_RES_CREATEPLAYER_ENUM = protobuf.EnumValueDescriptor()
localTable.RESPONSETYPE_RES_BATTLE_ENUM = protobuf.EnumValueDescriptor()
localTable.RESPONSETYPE_SEND_RELOGIN_ENUM = protobuf.EnumValueDescriptor()
G2CRESPONSE = protobuf.Descriptor()
localTable.G2CRESPONSE_MSGTYPE_FIELD = protobuf.FieldDescriptor()
localTable.G2CRESPONSE_MSGBODY_FIELD = protobuf.FieldDescriptor()
RES_HEARTBEATMSG = protobuf.Descriptor()
localTable.RES_HEARTBEATMSG_MSGTYPE_FIELD = protobuf.FieldDescriptor()
RES_LOGINMSG = protobuf.Descriptor()
localTable.RES_LOGINMSG_MSGTYPE_FIELD = protobuf.FieldDescriptor()
localTable.RES_LOGINMSG_RESCODE_FIELD = protobuf.FieldDescriptor()
localTable.RES_LOGINMSG_ERRMSG_FIELD = protobuf.FieldDescriptor()
localTable.RES_LOGINMSG_ISHAVEPLAYER_FIELD = protobuf.FieldDescriptor()
localTable.RES_LOGINMSG_PLAYERVO_FIELD = protobuf.FieldDescriptor()
localTable.RES_LOGINMSG_SESSIONID_FIELD = protobuf.FieldDescriptor()
RES_CREATEPLAYERMSG = protobuf.Descriptor()
localTable.RES_CREATEPLAYERMSG_MSGTYPE_FIELD = protobuf.FieldDescriptor()
localTable.RES_CREATEPLAYERMSG_RESCODE_FIELD = protobuf.FieldDescriptor()
localTable.RES_CREATEPLAYERMSG_ERRMSG_FIELD = protobuf.FieldDescriptor()
localTable.RES_CREATEPLAYERMSG_SESSIONID_FIELD = protobuf.FieldDescriptor()
localTable.RES_CREATEPLAYERMSG_PLAYERVO_FIELD = protobuf.FieldDescriptor()
RES_BATTLEMSG = protobuf.Descriptor()
localTable.RES_BATTLEMSG_MSGTYPE_FIELD = protobuf.FieldDescriptor()
localTable.RES_BATTLEMSG_RESCODE_FIELD = protobuf.FieldDescriptor()
localTable.RES_BATTLEMSG_ERRMSG_FIELD = protobuf.FieldDescriptor()
SEND_RELOGINMSG = protobuf.Descriptor()
localTable.SEND_RELOGINMSG_MSGTYPE_FIELD = protobuf.FieldDescriptor()
localTable.SEND_RELOGINMSG_ERRMSG_FIELD = protobuf.FieldDescriptor()

Res_Heartbeat = 1
Res_Login = 2
Res_CreatePlayer = 3
Res_Battle = 4
Send_ReLogin = 5001

localTable.RESPONSETYPE_RES_HEARTBEAT_ENUM.name = "Res_Heartbeat"
localTable.RESPONSETYPE_RES_HEARTBEAT_ENUM.index = 0
localTable.RESPONSETYPE_RES_HEARTBEAT_ENUM.number = 1
localTable.RESPONSETYPE_RES_LOGIN_ENUM.name = "Res_Login"
localTable.RESPONSETYPE_RES_LOGIN_ENUM.index = 1
localTable.RESPONSETYPE_RES_LOGIN_ENUM.number = 2
localTable.RESPONSETYPE_RES_CREATEPLAYER_ENUM.name = "Res_CreatePlayer"
localTable.RESPONSETYPE_RES_CREATEPLAYER_ENUM.index = 2
localTable.RESPONSETYPE_RES_CREATEPLAYER_ENUM.number = 3
localTable.RESPONSETYPE_RES_BATTLE_ENUM.name = "Res_Battle"
localTable.RESPONSETYPE_RES_BATTLE_ENUM.index = 3
localTable.RESPONSETYPE_RES_BATTLE_ENUM.number = 4
localTable.RESPONSETYPE_SEND_RELOGIN_ENUM.name = "Send_ReLogin"
localTable.RESPONSETYPE_SEND_RELOGIN_ENUM.index = 4
localTable.RESPONSETYPE_SEND_RELOGIN_ENUM.number = 5001
localTable.RESPONSETYPE.name = "ResponseType"
localTable.RESPONSETYPE.full_name = ".C2GResponseMsgProto.ResponseType"
localTable.RESPONSETYPE.values = {localTable.RESPONSETYPE_RES_HEARTBEAT_ENUM,localTable.RESPONSETYPE_RES_LOGIN_ENUM,localTable.RESPONSETYPE_RES_CREATEPLAYER_ENUM,localTable.RESPONSETYPE_RES_BATTLE_ENUM,localTable.RESPONSETYPE_SEND_RELOGIN_ENUM}
localTable.G2CRESPONSE_MSGTYPE_FIELD.name = "msgType"
localTable.G2CRESPONSE_MSGTYPE_FIELD.full_name = ".C2GResponseMsgProto.G2CResponse.msgType"
localTable.G2CRESPONSE_MSGTYPE_FIELD.number = 1
localTable.G2CRESPONSE_MSGTYPE_FIELD.index = 0
localTable.G2CRESPONSE_MSGTYPE_FIELD.label = 2
localTable.G2CRESPONSE_MSGTYPE_FIELD.has_default_value = false
localTable.G2CRESPONSE_MSGTYPE_FIELD.default_value = nil
localTable.G2CRESPONSE_MSGTYPE_FIELD.enum_type = localTable.RESPONSETYPE
localTable.G2CRESPONSE_MSGTYPE_FIELD.type = 14
localTable.G2CRESPONSE_MSGTYPE_FIELD.cpp_type = 8

localTable.G2CRESPONSE_MSGBODY_FIELD.name = "msgBody"
localTable.G2CRESPONSE_MSGBODY_FIELD.full_name = ".C2GResponseMsgProto.G2CResponse.msgBody"
localTable.G2CRESPONSE_MSGBODY_FIELD.number = 2
localTable.G2CRESPONSE_MSGBODY_FIELD.index = 1
localTable.G2CRESPONSE_MSGBODY_FIELD.label = 2
localTable.G2CRESPONSE_MSGBODY_FIELD.has_default_value = false
localTable.G2CRESPONSE_MSGBODY_FIELD.default_value = ""
localTable.G2CRESPONSE_MSGBODY_FIELD.type = 12
localTable.G2CRESPONSE_MSGBODY_FIELD.cpp_type = 9

G2CRESPONSE.name = "G2CResponse"
G2CRESPONSE.full_name = ".C2GResponseMsgProto.G2CResponse"
G2CRESPONSE.nested_types = {}
G2CRESPONSE.enum_types = {}
G2CRESPONSE.fields = {localTable.G2CRESPONSE_MSGTYPE_FIELD, localTable.G2CRESPONSE_MSGBODY_FIELD}
G2CRESPONSE.is_extendable = false
G2CRESPONSE.extensions = {}
localTable.RES_HEARTBEATMSG_MSGTYPE_FIELD.name = "msgType"
localTable.RES_HEARTBEATMSG_MSGTYPE_FIELD.full_name = ".C2GResponseMsgProto.Res_HeartbeatMsg.msgType"
localTable.RES_HEARTBEATMSG_MSGTYPE_FIELD.number = 1
localTable.RES_HEARTBEATMSG_MSGTYPE_FIELD.index = 0
localTable.RES_HEARTBEATMSG_MSGTYPE_FIELD.label = 1
localTable.RES_HEARTBEATMSG_MSGTYPE_FIELD.has_default_value = true
localTable.RES_HEARTBEATMSG_MSGTYPE_FIELD.default_value = Res_Heartbeat
localTable.RES_HEARTBEATMSG_MSGTYPE_FIELD.enum_type = localTable.RESPONSETYPE
localTable.RES_HEARTBEATMSG_MSGTYPE_FIELD.type = 14
localTable.RES_HEARTBEATMSG_MSGTYPE_FIELD.cpp_type = 8

RES_HEARTBEATMSG.name = "Res_HeartbeatMsg"
RES_HEARTBEATMSG.full_name = ".C2GResponseMsgProto.Res_HeartbeatMsg"
RES_HEARTBEATMSG.nested_types = {}
RES_HEARTBEATMSG.enum_types = {}
RES_HEARTBEATMSG.fields = {localTable.RES_HEARTBEATMSG_MSGTYPE_FIELD}
RES_HEARTBEATMSG.is_extendable = false
RES_HEARTBEATMSG.extensions = {}
localTable.RES_LOGINMSG_MSGTYPE_FIELD.name = "msgType"
localTable.RES_LOGINMSG_MSGTYPE_FIELD.full_name = ".C2GResponseMsgProto.Res_LoginMsg.msgType"
localTable.RES_LOGINMSG_MSGTYPE_FIELD.number = 1
localTable.RES_LOGINMSG_MSGTYPE_FIELD.index = 0
localTable.RES_LOGINMSG_MSGTYPE_FIELD.label = 1
localTable.RES_LOGINMSG_MSGTYPE_FIELD.has_default_value = true
localTable.RES_LOGINMSG_MSGTYPE_FIELD.default_value = Res_Login
localTable.RES_LOGINMSG_MSGTYPE_FIELD.enum_type = localTable.RESPONSETYPE
localTable.RES_LOGINMSG_MSGTYPE_FIELD.type = 14
localTable.RES_LOGINMSG_MSGTYPE_FIELD.cpp_type = 8

localTable.RES_LOGINMSG_RESCODE_FIELD.name = "resCode"
localTable.RES_LOGINMSG_RESCODE_FIELD.full_name = ".C2GResponseMsgProto.Res_LoginMsg.resCode"
localTable.RES_LOGINMSG_RESCODE_FIELD.number = 2
localTable.RES_LOGINMSG_RESCODE_FIELD.index = 1
localTable.RES_LOGINMSG_RESCODE_FIELD.label = 1
localTable.RES_LOGINMSG_RESCODE_FIELD.has_default_value = false
localTable.RES_LOGINMSG_RESCODE_FIELD.default_value = ""
localTable.RES_LOGINMSG_RESCODE_FIELD.type = 9
localTable.RES_LOGINMSG_RESCODE_FIELD.cpp_type = 9

localTable.RES_LOGINMSG_ERRMSG_FIELD.name = "errMsg"
localTable.RES_LOGINMSG_ERRMSG_FIELD.full_name = ".C2GResponseMsgProto.Res_LoginMsg.errMsg"
localTable.RES_LOGINMSG_ERRMSG_FIELD.number = 3
localTable.RES_LOGINMSG_ERRMSG_FIELD.index = 2
localTable.RES_LOGINMSG_ERRMSG_FIELD.label = 1
localTable.RES_LOGINMSG_ERRMSG_FIELD.has_default_value = false
localTable.RES_LOGINMSG_ERRMSG_FIELD.default_value = ""
localTable.RES_LOGINMSG_ERRMSG_FIELD.type = 9
localTable.RES_LOGINMSG_ERRMSG_FIELD.cpp_type = 9

localTable.RES_LOGINMSG_ISHAVEPLAYER_FIELD.name = "isHavePlayer"
localTable.RES_LOGINMSG_ISHAVEPLAYER_FIELD.full_name = ".C2GResponseMsgProto.Res_LoginMsg.isHavePlayer"
localTable.RES_LOGINMSG_ISHAVEPLAYER_FIELD.number = 4
localTable.RES_LOGINMSG_ISHAVEPLAYER_FIELD.index = 3
localTable.RES_LOGINMSG_ISHAVEPLAYER_FIELD.label = 1
localTable.RES_LOGINMSG_ISHAVEPLAYER_FIELD.has_default_value = false
localTable.RES_LOGINMSG_ISHAVEPLAYER_FIELD.default_value = false
localTable.RES_LOGINMSG_ISHAVEPLAYER_FIELD.type = 8
localTable.RES_LOGINMSG_ISHAVEPLAYER_FIELD.cpp_type = 7

localTable.RES_LOGINMSG_PLAYERVO_FIELD.name = "playerVO"
localTable.RES_LOGINMSG_PLAYERVO_FIELD.full_name = ".C2GResponseMsgProto.Res_LoginMsg.playerVO"
localTable.RES_LOGINMSG_PLAYERVO_FIELD.number = 5
localTable.RES_LOGINMSG_PLAYERVO_FIELD.index = 4
localTable.RES_LOGINMSG_PLAYERVO_FIELD.label = 1
localTable.RES_LOGINMSG_PLAYERVO_FIELD.has_default_value = false
localTable.RES_LOGINMSG_PLAYERVO_FIELD.default_value = nil
localTable.RES_LOGINMSG_PLAYERVO_FIELD.message_type = VO_PB.PLAYERVO
localTable.RES_LOGINMSG_PLAYERVO_FIELD.type = 11
localTable.RES_LOGINMSG_PLAYERVO_FIELD.cpp_type = 10

localTable.RES_LOGINMSG_SESSIONID_FIELD.name = "sessionId"
localTable.RES_LOGINMSG_SESSIONID_FIELD.full_name = ".C2GResponseMsgProto.Res_LoginMsg.sessionId"
localTable.RES_LOGINMSG_SESSIONID_FIELD.number = 6
localTable.RES_LOGINMSG_SESSIONID_FIELD.index = 5
localTable.RES_LOGINMSG_SESSIONID_FIELD.label = 1
localTable.RES_LOGINMSG_SESSIONID_FIELD.has_default_value = false
localTable.RES_LOGINMSG_SESSIONID_FIELD.default_value = ""
localTable.RES_LOGINMSG_SESSIONID_FIELD.type = 9
localTable.RES_LOGINMSG_SESSIONID_FIELD.cpp_type = 9

RES_LOGINMSG.name = "Res_LoginMsg"
RES_LOGINMSG.full_name = ".C2GResponseMsgProto.Res_LoginMsg"
RES_LOGINMSG.nested_types = {}
RES_LOGINMSG.enum_types = {}
RES_LOGINMSG.fields = {localTable.RES_LOGINMSG_MSGTYPE_FIELD, localTable.RES_LOGINMSG_RESCODE_FIELD, localTable.RES_LOGINMSG_ERRMSG_FIELD, localTable.RES_LOGINMSG_ISHAVEPLAYER_FIELD, localTable.RES_LOGINMSG_PLAYERVO_FIELD, localTable.RES_LOGINMSG_SESSIONID_FIELD}
RES_LOGINMSG.is_extendable = false
RES_LOGINMSG.extensions = {}
localTable.RES_CREATEPLAYERMSG_MSGTYPE_FIELD.name = "msgType"
localTable.RES_CREATEPLAYERMSG_MSGTYPE_FIELD.full_name = ".C2GResponseMsgProto.Res_CreatePlayerMsg.msgType"
localTable.RES_CREATEPLAYERMSG_MSGTYPE_FIELD.number = 1
localTable.RES_CREATEPLAYERMSG_MSGTYPE_FIELD.index = 0
localTable.RES_CREATEPLAYERMSG_MSGTYPE_FIELD.label = 1
localTable.RES_CREATEPLAYERMSG_MSGTYPE_FIELD.has_default_value = true
localTable.RES_CREATEPLAYERMSG_MSGTYPE_FIELD.default_value = Res_CreatePlayer
localTable.RES_CREATEPLAYERMSG_MSGTYPE_FIELD.enum_type = localTable.RESPONSETYPE
localTable.RES_CREATEPLAYERMSG_MSGTYPE_FIELD.type = 14
localTable.RES_CREATEPLAYERMSG_MSGTYPE_FIELD.cpp_type = 8

localTable.RES_CREATEPLAYERMSG_RESCODE_FIELD.name = "resCode"
localTable.RES_CREATEPLAYERMSG_RESCODE_FIELD.full_name = ".C2GResponseMsgProto.Res_CreatePlayerMsg.resCode"
localTable.RES_CREATEPLAYERMSG_RESCODE_FIELD.number = 2
localTable.RES_CREATEPLAYERMSG_RESCODE_FIELD.index = 1
localTable.RES_CREATEPLAYERMSG_RESCODE_FIELD.label = 1
localTable.RES_CREATEPLAYERMSG_RESCODE_FIELD.has_default_value = false
localTable.RES_CREATEPLAYERMSG_RESCODE_FIELD.default_value = ""
localTable.RES_CREATEPLAYERMSG_RESCODE_FIELD.type = 9
localTable.RES_CREATEPLAYERMSG_RESCODE_FIELD.cpp_type = 9

localTable.RES_CREATEPLAYERMSG_ERRMSG_FIELD.name = "errMsg"
localTable.RES_CREATEPLAYERMSG_ERRMSG_FIELD.full_name = ".C2GResponseMsgProto.Res_CreatePlayerMsg.errMsg"
localTable.RES_CREATEPLAYERMSG_ERRMSG_FIELD.number = 3
localTable.RES_CREATEPLAYERMSG_ERRMSG_FIELD.index = 2
localTable.RES_CREATEPLAYERMSG_ERRMSG_FIELD.label = 1
localTable.RES_CREATEPLAYERMSG_ERRMSG_FIELD.has_default_value = false
localTable.RES_CREATEPLAYERMSG_ERRMSG_FIELD.default_value = ""
localTable.RES_CREATEPLAYERMSG_ERRMSG_FIELD.type = 9
localTable.RES_CREATEPLAYERMSG_ERRMSG_FIELD.cpp_type = 9

localTable.RES_CREATEPLAYERMSG_SESSIONID_FIELD.name = "sessionId"
localTable.RES_CREATEPLAYERMSG_SESSIONID_FIELD.full_name = ".C2GResponseMsgProto.Res_CreatePlayerMsg.sessionId"
localTable.RES_CREATEPLAYERMSG_SESSIONID_FIELD.number = 4
localTable.RES_CREATEPLAYERMSG_SESSIONID_FIELD.index = 3
localTable.RES_CREATEPLAYERMSG_SESSIONID_FIELD.label = 1
localTable.RES_CREATEPLAYERMSG_SESSIONID_FIELD.has_default_value = false
localTable.RES_CREATEPLAYERMSG_SESSIONID_FIELD.default_value = ""
localTable.RES_CREATEPLAYERMSG_SESSIONID_FIELD.type = 9
localTable.RES_CREATEPLAYERMSG_SESSIONID_FIELD.cpp_type = 9

localTable.RES_CREATEPLAYERMSG_PLAYERVO_FIELD.name = "playerVO"
localTable.RES_CREATEPLAYERMSG_PLAYERVO_FIELD.full_name = ".C2GResponseMsgProto.Res_CreatePlayerMsg.playerVO"
localTable.RES_CREATEPLAYERMSG_PLAYERVO_FIELD.number = 5
localTable.RES_CREATEPLAYERMSG_PLAYERVO_FIELD.index = 4
localTable.RES_CREATEPLAYERMSG_PLAYERVO_FIELD.label = 1
localTable.RES_CREATEPLAYERMSG_PLAYERVO_FIELD.has_default_value = false
localTable.RES_CREATEPLAYERMSG_PLAYERVO_FIELD.default_value = nil
localTable.RES_CREATEPLAYERMSG_PLAYERVO_FIELD.message_type = VO_PB.PLAYERVO
localTable.RES_CREATEPLAYERMSG_PLAYERVO_FIELD.type = 11
localTable.RES_CREATEPLAYERMSG_PLAYERVO_FIELD.cpp_type = 10

RES_CREATEPLAYERMSG.name = "Res_CreatePlayerMsg"
RES_CREATEPLAYERMSG.full_name = ".C2GResponseMsgProto.Res_CreatePlayerMsg"
RES_CREATEPLAYERMSG.nested_types = {}
RES_CREATEPLAYERMSG.enum_types = {}
RES_CREATEPLAYERMSG.fields = {localTable.RES_CREATEPLAYERMSG_MSGTYPE_FIELD, localTable.RES_CREATEPLAYERMSG_RESCODE_FIELD, localTable.RES_CREATEPLAYERMSG_ERRMSG_FIELD, localTable.RES_CREATEPLAYERMSG_SESSIONID_FIELD, localTable.RES_CREATEPLAYERMSG_PLAYERVO_FIELD}
RES_CREATEPLAYERMSG.is_extendable = false
RES_CREATEPLAYERMSG.extensions = {}
localTable.RES_BATTLEMSG_MSGTYPE_FIELD.name = "msgType"
localTable.RES_BATTLEMSG_MSGTYPE_FIELD.full_name = ".C2GResponseMsgProto.Res_BattleMsg.msgType"
localTable.RES_BATTLEMSG_MSGTYPE_FIELD.number = 1
localTable.RES_BATTLEMSG_MSGTYPE_FIELD.index = 0
localTable.RES_BATTLEMSG_MSGTYPE_FIELD.label = 1
localTable.RES_BATTLEMSG_MSGTYPE_FIELD.has_default_value = true
localTable.RES_BATTLEMSG_MSGTYPE_FIELD.default_value = Res_Battle
localTable.RES_BATTLEMSG_MSGTYPE_FIELD.enum_type = localTable.RESPONSETYPE
localTable.RES_BATTLEMSG_MSGTYPE_FIELD.type = 14
localTable.RES_BATTLEMSG_MSGTYPE_FIELD.cpp_type = 8

localTable.RES_BATTLEMSG_RESCODE_FIELD.name = "resCode"
localTable.RES_BATTLEMSG_RESCODE_FIELD.full_name = ".C2GResponseMsgProto.Res_BattleMsg.resCode"
localTable.RES_BATTLEMSG_RESCODE_FIELD.number = 2
localTable.RES_BATTLEMSG_RESCODE_FIELD.index = 1
localTable.RES_BATTLEMSG_RESCODE_FIELD.label = 1
localTable.RES_BATTLEMSG_RESCODE_FIELD.has_default_value = false
localTable.RES_BATTLEMSG_RESCODE_FIELD.default_value = ""
localTable.RES_BATTLEMSG_RESCODE_FIELD.type = 9
localTable.RES_BATTLEMSG_RESCODE_FIELD.cpp_type = 9

localTable.RES_BATTLEMSG_ERRMSG_FIELD.name = "errMsg"
localTable.RES_BATTLEMSG_ERRMSG_FIELD.full_name = ".C2GResponseMsgProto.Res_BattleMsg.errMsg"
localTable.RES_BATTLEMSG_ERRMSG_FIELD.number = 3
localTable.RES_BATTLEMSG_ERRMSG_FIELD.index = 2
localTable.RES_BATTLEMSG_ERRMSG_FIELD.label = 1
localTable.RES_BATTLEMSG_ERRMSG_FIELD.has_default_value = false
localTable.RES_BATTLEMSG_ERRMSG_FIELD.default_value = ""
localTable.RES_BATTLEMSG_ERRMSG_FIELD.type = 9
localTable.RES_BATTLEMSG_ERRMSG_FIELD.cpp_type = 9

RES_BATTLEMSG.name = "Res_BattleMsg"
RES_BATTLEMSG.full_name = ".C2GResponseMsgProto.Res_BattleMsg"
RES_BATTLEMSG.nested_types = {}
RES_BATTLEMSG.enum_types = {}
RES_BATTLEMSG.fields = {localTable.RES_BATTLEMSG_MSGTYPE_FIELD, localTable.RES_BATTLEMSG_RESCODE_FIELD, localTable.RES_BATTLEMSG_ERRMSG_FIELD}
RES_BATTLEMSG.is_extendable = false
RES_BATTLEMSG.extensions = {}
localTable.SEND_RELOGINMSG_MSGTYPE_FIELD.name = "msgType"
localTable.SEND_RELOGINMSG_MSGTYPE_FIELD.full_name = ".C2GResponseMsgProto.Send_ReLoginMsg.msgType"
localTable.SEND_RELOGINMSG_MSGTYPE_FIELD.number = 1
localTable.SEND_RELOGINMSG_MSGTYPE_FIELD.index = 0
localTable.SEND_RELOGINMSG_MSGTYPE_FIELD.label = 1
localTable.SEND_RELOGINMSG_MSGTYPE_FIELD.has_default_value = true
localTable.SEND_RELOGINMSG_MSGTYPE_FIELD.default_value = Send_ReLogin
localTable.SEND_RELOGINMSG_MSGTYPE_FIELD.enum_type = localTable.RESPONSETYPE
localTable.SEND_RELOGINMSG_MSGTYPE_FIELD.type = 14
localTable.SEND_RELOGINMSG_MSGTYPE_FIELD.cpp_type = 8

localTable.SEND_RELOGINMSG_ERRMSG_FIELD.name = "errMsg"
localTable.SEND_RELOGINMSG_ERRMSG_FIELD.full_name = ".C2GResponseMsgProto.Send_ReLoginMsg.errMsg"
localTable.SEND_RELOGINMSG_ERRMSG_FIELD.number = 2
localTable.SEND_RELOGINMSG_ERRMSG_FIELD.index = 1
localTable.SEND_RELOGINMSG_ERRMSG_FIELD.label = 1
localTable.SEND_RELOGINMSG_ERRMSG_FIELD.has_default_value = false
localTable.SEND_RELOGINMSG_ERRMSG_FIELD.default_value = ""
localTable.SEND_RELOGINMSG_ERRMSG_FIELD.type = 9
localTable.SEND_RELOGINMSG_ERRMSG_FIELD.cpp_type = 9

SEND_RELOGINMSG.name = "Send_ReLoginMsg"
SEND_RELOGINMSG.full_name = ".C2GResponseMsgProto.Send_ReLoginMsg"
SEND_RELOGINMSG.nested_types = {}
SEND_RELOGINMSG.enum_types = {}
SEND_RELOGINMSG.fields = {localTable.SEND_RELOGINMSG_MSGTYPE_FIELD, localTable.SEND_RELOGINMSG_ERRMSG_FIELD}
SEND_RELOGINMSG.is_extendable = false
SEND_RELOGINMSG.extensions = {}

-- msgType, 
Res_HeartbeatMsg = protobuf.Message(RES_HEARTBEATMSG)

-- msgType, errMsg, 
Send_ReLoginMsg = protobuf.Message(SEND_RELOGINMSG)

-- msgType, msgBody, 
G2CResponse = protobuf.Message(G2CRESPONSE)

-- msgType, resCode, errMsg, 
Res_BattleMsg = protobuf.Message(RES_BATTLEMSG)

-- msgType, resCode, errMsg, isHavePlayer, playerVO, sessionId, 
Res_LoginMsg = protobuf.Message(RES_LOGINMSG)

-- msgType, resCode, errMsg, sessionId, playerVO, 
Res_CreatePlayerMsg = protobuf.Message(RES_CREATEPLAYERMSG)


return m_table