-- Generated By protoc-gen-lua do no edit
local protobuf = require "protobuf/protobuf"
local m_table = {}
setmetatable(m_table,{__index = _G})
local _ENV = m_table

local localTable = {}
ACCOUNTVO = protobuf.Descriptor()
localTable.ACCOUNTVO_ACCOUNTID_FIELD = protobuf.FieldDescriptor()
localTable.ACCOUNTVO_ACCOUNTNAME_FIELD = protobuf.FieldDescriptor()
localTable.ACCOUNTVO_PASSWORD_FIELD = protobuf.FieldDescriptor()
localTable.ACCOUNTVO_DEVICEIID_FIELD = protobuf.FieldDescriptor()
localTable.ACCOUNTVO_PLATFORM_FIELD = protobuf.FieldDescriptor()
localTable.ACCOUNTVO_CREATETIME_FIELD = protobuf.FieldDescriptor()
localTable.ACCOUNTVO_LASTLOGINTIME_FIELD = protobuf.FieldDescriptor()
localTable.ACCOUNTVO_STATUS_FIELD = protobuf.FieldDescriptor()
localTable.ACCOUNTVO_BANBEGINTIME_FIELD = protobuf.FieldDescriptor()
localTable.ACCOUNTVO_BANENDTIME_FIELD = protobuf.FieldDescriptor()
localTable.ACCOUNTVO_LASTLOGINIP_FIELD = protobuf.FieldDescriptor()
PLAYERVO = protobuf.Descriptor()
localTable.PLAYERVO_ACCOUNTID_FIELD = protobuf.FieldDescriptor()
localTable.PLAYERVO_ACCOUNTNAME_FIELD = protobuf.FieldDescriptor()
localTable.PLAYERVO_PLATFORM_FIELD = protobuf.FieldDescriptor()
localTable.PLAYERVO_PLAYERID_FIELD = protobuf.FieldDescriptor()
localTable.PLAYERVO_PLAYERNAME_FIELD = protobuf.FieldDescriptor()
localTable.PLAYERVO_SEX_FIELD = protobuf.FieldDescriptor()
localTable.PLAYERVO_MONEY_FIELD = protobuf.FieldDescriptor()
localTable.PLAYERVO_CASH_FIELD = protobuf.FieldDescriptor()
localTable.PLAYERVO_ENERGY_FIELD = protobuf.FieldDescriptor()
localTable.PLAYERVO_CARDS_FIELD = protobuf.FieldDescriptor()
localTable.PLAYERVO_PVECARDS_FIELD = protobuf.FieldDescriptor()
localTable.PLAYERVO_PVPCARDS_FIELD = protobuf.FieldDescriptor()
localTable.PLAYERVO_LASTLOGINTIME_FIELD = protobuf.FieldDescriptor()
localTable.PLAYERVO_LASTLOGOUTTIME_FIELD = protobuf.FieldDescriptor()
UNITVO = protobuf.Descriptor()
localTable.UNITVO_SN_FIELD = protobuf.FieldDescriptor()
localTable.UNITVO_ID_FIELD = protobuf.FieldDescriptor()
localTable.UNITVO_LEVEL_FIELD = protobuf.FieldDescriptor()
localTable.UNITVO_EXP_FIELD = protobuf.FieldDescriptor()
localTable.UNITVO_STAR_FIELD = protobuf.FieldDescriptor()
localTable.UNITVO_SKILLS_FIELD = protobuf.FieldDescriptor()
localTable.UNITVO_BORNTIME_FIELD = protobuf.FieldDescriptor()
SKILLVO = protobuf.Descriptor()
localTable.SKILLVO_ID_FIELD = protobuf.FieldDescriptor()
localTable.SKILLVO_LEVEL_FIELD = protobuf.FieldDescriptor()
FORMATIONVO = protobuf.Descriptor()
localTable.FORMATIONVO_ID_FIELD = protobuf.FieldDescriptor()
localTable.FORMATIONVO_ISALTERNATE_FIELD = protobuf.FieldDescriptor()
BATTLEINFOVO = protobuf.Descriptor()
localTable.BATTLEINFOVO_SECTION_FIELD = protobuf.FieldDescriptor()
localTable.BATTLEINFOVO_FRAME_FIELD = protobuf.FieldDescriptor()
localTable.BATTLEINFOVO_TYPE_FIELD = protobuf.FieldDescriptor()
localTable.BATTLEINFOVO_PARAM_FIELD = protobuf.FieldDescriptor()


localTable.ACCOUNTVO_ACCOUNTID_FIELD.name = "accountId"
localTable.ACCOUNTVO_ACCOUNTID_FIELD.full_name = ".VO.AccountVO.accountId"
localTable.ACCOUNTVO_ACCOUNTID_FIELD.number = 1
localTable.ACCOUNTVO_ACCOUNTID_FIELD.index = 0
localTable.ACCOUNTVO_ACCOUNTID_FIELD.label = 1
localTable.ACCOUNTVO_ACCOUNTID_FIELD.has_default_value = false
localTable.ACCOUNTVO_ACCOUNTID_FIELD.default_value = ""
localTable.ACCOUNTVO_ACCOUNTID_FIELD.type = 9
localTable.ACCOUNTVO_ACCOUNTID_FIELD.cpp_type = 9

localTable.ACCOUNTVO_ACCOUNTNAME_FIELD.name = "accountName"
localTable.ACCOUNTVO_ACCOUNTNAME_FIELD.full_name = ".VO.AccountVO.accountName"
localTable.ACCOUNTVO_ACCOUNTNAME_FIELD.number = 2
localTable.ACCOUNTVO_ACCOUNTNAME_FIELD.index = 1
localTable.ACCOUNTVO_ACCOUNTNAME_FIELD.label = 1
localTable.ACCOUNTVO_ACCOUNTNAME_FIELD.has_default_value = false
localTable.ACCOUNTVO_ACCOUNTNAME_FIELD.default_value = ""
localTable.ACCOUNTVO_ACCOUNTNAME_FIELD.type = 9
localTable.ACCOUNTVO_ACCOUNTNAME_FIELD.cpp_type = 9

localTable.ACCOUNTVO_PASSWORD_FIELD.name = "password"
localTable.ACCOUNTVO_PASSWORD_FIELD.full_name = ".VO.AccountVO.password"
localTable.ACCOUNTVO_PASSWORD_FIELD.number = 3
localTable.ACCOUNTVO_PASSWORD_FIELD.index = 2
localTable.ACCOUNTVO_PASSWORD_FIELD.label = 1
localTable.ACCOUNTVO_PASSWORD_FIELD.has_default_value = false
localTable.ACCOUNTVO_PASSWORD_FIELD.default_value = ""
localTable.ACCOUNTVO_PASSWORD_FIELD.type = 9
localTable.ACCOUNTVO_PASSWORD_FIELD.cpp_type = 9

localTable.ACCOUNTVO_DEVICEIID_FIELD.name = "deviceIId"
localTable.ACCOUNTVO_DEVICEIID_FIELD.full_name = ".VO.AccountVO.deviceIId"
localTable.ACCOUNTVO_DEVICEIID_FIELD.number = 4
localTable.ACCOUNTVO_DEVICEIID_FIELD.index = 3
localTable.ACCOUNTVO_DEVICEIID_FIELD.label = 1
localTable.ACCOUNTVO_DEVICEIID_FIELD.has_default_value = false
localTable.ACCOUNTVO_DEVICEIID_FIELD.default_value = ""
localTable.ACCOUNTVO_DEVICEIID_FIELD.type = 9
localTable.ACCOUNTVO_DEVICEIID_FIELD.cpp_type = 9

localTable.ACCOUNTVO_PLATFORM_FIELD.name = "platform"
localTable.ACCOUNTVO_PLATFORM_FIELD.full_name = ".VO.AccountVO.platform"
localTable.ACCOUNTVO_PLATFORM_FIELD.number = 5
localTable.ACCOUNTVO_PLATFORM_FIELD.index = 4
localTable.ACCOUNTVO_PLATFORM_FIELD.label = 1
localTable.ACCOUNTVO_PLATFORM_FIELD.has_default_value = false
localTable.ACCOUNTVO_PLATFORM_FIELD.default_value = ""
localTable.ACCOUNTVO_PLATFORM_FIELD.type = 9
localTable.ACCOUNTVO_PLATFORM_FIELD.cpp_type = 9

localTable.ACCOUNTVO_CREATETIME_FIELD.name = "createTime"
localTable.ACCOUNTVO_CREATETIME_FIELD.full_name = ".VO.AccountVO.createTime"
localTable.ACCOUNTVO_CREATETIME_FIELD.number = 6
localTable.ACCOUNTVO_CREATETIME_FIELD.index = 5
localTable.ACCOUNTVO_CREATETIME_FIELD.label = 1
localTable.ACCOUNTVO_CREATETIME_FIELD.has_default_value = false
localTable.ACCOUNTVO_CREATETIME_FIELD.default_value = 0
localTable.ACCOUNTVO_CREATETIME_FIELD.type = 3
localTable.ACCOUNTVO_CREATETIME_FIELD.cpp_type = 2

localTable.ACCOUNTVO_LASTLOGINTIME_FIELD.name = "lastLoginTime"
localTable.ACCOUNTVO_LASTLOGINTIME_FIELD.full_name = ".VO.AccountVO.lastLoginTime"
localTable.ACCOUNTVO_LASTLOGINTIME_FIELD.number = 7
localTable.ACCOUNTVO_LASTLOGINTIME_FIELD.index = 6
localTable.ACCOUNTVO_LASTLOGINTIME_FIELD.label = 1
localTable.ACCOUNTVO_LASTLOGINTIME_FIELD.has_default_value = false
localTable.ACCOUNTVO_LASTLOGINTIME_FIELD.default_value = 0
localTable.ACCOUNTVO_LASTLOGINTIME_FIELD.type = 3
localTable.ACCOUNTVO_LASTLOGINTIME_FIELD.cpp_type = 2

localTable.ACCOUNTVO_STATUS_FIELD.name = "status"
localTable.ACCOUNTVO_STATUS_FIELD.full_name = ".VO.AccountVO.status"
localTable.ACCOUNTVO_STATUS_FIELD.number = 8
localTable.ACCOUNTVO_STATUS_FIELD.index = 7
localTable.ACCOUNTVO_STATUS_FIELD.label = 1
localTable.ACCOUNTVO_STATUS_FIELD.has_default_value = false
localTable.ACCOUNTVO_STATUS_FIELD.default_value = 0
localTable.ACCOUNTVO_STATUS_FIELD.type = 5
localTable.ACCOUNTVO_STATUS_FIELD.cpp_type = 1

localTable.ACCOUNTVO_BANBEGINTIME_FIELD.name = "banBeginTime"
localTable.ACCOUNTVO_BANBEGINTIME_FIELD.full_name = ".VO.AccountVO.banBeginTime"
localTable.ACCOUNTVO_BANBEGINTIME_FIELD.number = 9
localTable.ACCOUNTVO_BANBEGINTIME_FIELD.index = 8
localTable.ACCOUNTVO_BANBEGINTIME_FIELD.label = 1
localTable.ACCOUNTVO_BANBEGINTIME_FIELD.has_default_value = false
localTable.ACCOUNTVO_BANBEGINTIME_FIELD.default_value = 0
localTable.ACCOUNTVO_BANBEGINTIME_FIELD.type = 3
localTable.ACCOUNTVO_BANBEGINTIME_FIELD.cpp_type = 2

localTable.ACCOUNTVO_BANENDTIME_FIELD.name = "banEndTime"
localTable.ACCOUNTVO_BANENDTIME_FIELD.full_name = ".VO.AccountVO.banEndTime"
localTable.ACCOUNTVO_BANENDTIME_FIELD.number = 10
localTable.ACCOUNTVO_BANENDTIME_FIELD.index = 9
localTable.ACCOUNTVO_BANENDTIME_FIELD.label = 1
localTable.ACCOUNTVO_BANENDTIME_FIELD.has_default_value = false
localTable.ACCOUNTVO_BANENDTIME_FIELD.default_value = 0
localTable.ACCOUNTVO_BANENDTIME_FIELD.type = 3
localTable.ACCOUNTVO_BANENDTIME_FIELD.cpp_type = 2

localTable.ACCOUNTVO_LASTLOGINIP_FIELD.name = "lastLoginIp"
localTable.ACCOUNTVO_LASTLOGINIP_FIELD.full_name = ".VO.AccountVO.lastLoginIp"
localTable.ACCOUNTVO_LASTLOGINIP_FIELD.number = 11
localTable.ACCOUNTVO_LASTLOGINIP_FIELD.index = 10
localTable.ACCOUNTVO_LASTLOGINIP_FIELD.label = 1
localTable.ACCOUNTVO_LASTLOGINIP_FIELD.has_default_value = false
localTable.ACCOUNTVO_LASTLOGINIP_FIELD.default_value = ""
localTable.ACCOUNTVO_LASTLOGINIP_FIELD.type = 9
localTable.ACCOUNTVO_LASTLOGINIP_FIELD.cpp_type = 9

ACCOUNTVO.name = "AccountVO"
ACCOUNTVO.full_name = ".VO.AccountVO"
ACCOUNTVO.nested_types = {}
ACCOUNTVO.enum_types = {}
ACCOUNTVO.fields = {localTable.ACCOUNTVO_ACCOUNTID_FIELD, localTable.ACCOUNTVO_ACCOUNTNAME_FIELD, localTable.ACCOUNTVO_PASSWORD_FIELD, localTable.ACCOUNTVO_DEVICEIID_FIELD, localTable.ACCOUNTVO_PLATFORM_FIELD, localTable.ACCOUNTVO_CREATETIME_FIELD, localTable.ACCOUNTVO_LASTLOGINTIME_FIELD, localTable.ACCOUNTVO_STATUS_FIELD, localTable.ACCOUNTVO_BANBEGINTIME_FIELD, localTable.ACCOUNTVO_BANENDTIME_FIELD, localTable.ACCOUNTVO_LASTLOGINIP_FIELD}
ACCOUNTVO.is_extendable = false
ACCOUNTVO.extensions = {}
localTable.PLAYERVO_ACCOUNTID_FIELD.name = "accountId"
localTable.PLAYERVO_ACCOUNTID_FIELD.full_name = ".VO.PlayerVO.accountId"
localTable.PLAYERVO_ACCOUNTID_FIELD.number = 1
localTable.PLAYERVO_ACCOUNTID_FIELD.index = 0
localTable.PLAYERVO_ACCOUNTID_FIELD.label = 1
localTable.PLAYERVO_ACCOUNTID_FIELD.has_default_value = false
localTable.PLAYERVO_ACCOUNTID_FIELD.default_value = ""
localTable.PLAYERVO_ACCOUNTID_FIELD.type = 9
localTable.PLAYERVO_ACCOUNTID_FIELD.cpp_type = 9

localTable.PLAYERVO_ACCOUNTNAME_FIELD.name = "accountName"
localTable.PLAYERVO_ACCOUNTNAME_FIELD.full_name = ".VO.PlayerVO.accountName"
localTable.PLAYERVO_ACCOUNTNAME_FIELD.number = 2
localTable.PLAYERVO_ACCOUNTNAME_FIELD.index = 1
localTable.PLAYERVO_ACCOUNTNAME_FIELD.label = 1
localTable.PLAYERVO_ACCOUNTNAME_FIELD.has_default_value = false
localTable.PLAYERVO_ACCOUNTNAME_FIELD.default_value = ""
localTable.PLAYERVO_ACCOUNTNAME_FIELD.type = 9
localTable.PLAYERVO_ACCOUNTNAME_FIELD.cpp_type = 9

localTable.PLAYERVO_PLATFORM_FIELD.name = "platform"
localTable.PLAYERVO_PLATFORM_FIELD.full_name = ".VO.PlayerVO.platform"
localTable.PLAYERVO_PLATFORM_FIELD.number = 3
localTable.PLAYERVO_PLATFORM_FIELD.index = 2
localTable.PLAYERVO_PLATFORM_FIELD.label = 1
localTable.PLAYERVO_PLATFORM_FIELD.has_default_value = false
localTable.PLAYERVO_PLATFORM_FIELD.default_value = ""
localTable.PLAYERVO_PLATFORM_FIELD.type = 9
localTable.PLAYERVO_PLATFORM_FIELD.cpp_type = 9

localTable.PLAYERVO_PLAYERID_FIELD.name = "playerId"
localTable.PLAYERVO_PLAYERID_FIELD.full_name = ".VO.PlayerVO.playerId"
localTable.PLAYERVO_PLAYERID_FIELD.number = 4
localTable.PLAYERVO_PLAYERID_FIELD.index = 3
localTable.PLAYERVO_PLAYERID_FIELD.label = 1
localTable.PLAYERVO_PLAYERID_FIELD.has_default_value = false
localTable.PLAYERVO_PLAYERID_FIELD.default_value = ""
localTable.PLAYERVO_PLAYERID_FIELD.type = 9
localTable.PLAYERVO_PLAYERID_FIELD.cpp_type = 9

localTable.PLAYERVO_PLAYERNAME_FIELD.name = "playerName"
localTable.PLAYERVO_PLAYERNAME_FIELD.full_name = ".VO.PlayerVO.playerName"
localTable.PLAYERVO_PLAYERNAME_FIELD.number = 5
localTable.PLAYERVO_PLAYERNAME_FIELD.index = 4
localTable.PLAYERVO_PLAYERNAME_FIELD.label = 1
localTable.PLAYERVO_PLAYERNAME_FIELD.has_default_value = false
localTable.PLAYERVO_PLAYERNAME_FIELD.default_value = ""
localTable.PLAYERVO_PLAYERNAME_FIELD.type = 9
localTable.PLAYERVO_PLAYERNAME_FIELD.cpp_type = 9

localTable.PLAYERVO_SEX_FIELD.name = "sex"
localTable.PLAYERVO_SEX_FIELD.full_name = ".VO.PlayerVO.sex"
localTable.PLAYERVO_SEX_FIELD.number = 6
localTable.PLAYERVO_SEX_FIELD.index = 5
localTable.PLAYERVO_SEX_FIELD.label = 1
localTable.PLAYERVO_SEX_FIELD.has_default_value = false
localTable.PLAYERVO_SEX_FIELD.default_value = 0
localTable.PLAYERVO_SEX_FIELD.type = 5
localTable.PLAYERVO_SEX_FIELD.cpp_type = 1

localTable.PLAYERVO_MONEY_FIELD.name = "money"
localTable.PLAYERVO_MONEY_FIELD.full_name = ".VO.PlayerVO.money"
localTable.PLAYERVO_MONEY_FIELD.number = 9
localTable.PLAYERVO_MONEY_FIELD.index = 6
localTable.PLAYERVO_MONEY_FIELD.label = 1
localTable.PLAYERVO_MONEY_FIELD.has_default_value = false
localTable.PLAYERVO_MONEY_FIELD.default_value = 0
localTable.PLAYERVO_MONEY_FIELD.type = 3
localTable.PLAYERVO_MONEY_FIELD.cpp_type = 2

localTable.PLAYERVO_CASH_FIELD.name = "cash"
localTable.PLAYERVO_CASH_FIELD.full_name = ".VO.PlayerVO.cash"
localTable.PLAYERVO_CASH_FIELD.number = 10
localTable.PLAYERVO_CASH_FIELD.index = 7
localTable.PLAYERVO_CASH_FIELD.label = 1
localTable.PLAYERVO_CASH_FIELD.has_default_value = false
localTable.PLAYERVO_CASH_FIELD.default_value = 0
localTable.PLAYERVO_CASH_FIELD.type = 3
localTable.PLAYERVO_CASH_FIELD.cpp_type = 2

localTable.PLAYERVO_ENERGY_FIELD.name = "energy"
localTable.PLAYERVO_ENERGY_FIELD.full_name = ".VO.PlayerVO.energy"
localTable.PLAYERVO_ENERGY_FIELD.number = 11
localTable.PLAYERVO_ENERGY_FIELD.index = 8
localTable.PLAYERVO_ENERGY_FIELD.label = 1
localTable.PLAYERVO_ENERGY_FIELD.has_default_value = false
localTable.PLAYERVO_ENERGY_FIELD.default_value = 0
localTable.PLAYERVO_ENERGY_FIELD.type = 5
localTable.PLAYERVO_ENERGY_FIELD.cpp_type = 1

localTable.PLAYERVO_CARDS_FIELD.name = "cards"
localTable.PLAYERVO_CARDS_FIELD.full_name = ".VO.PlayerVO.cards"
localTable.PLAYERVO_CARDS_FIELD.number = 21
localTable.PLAYERVO_CARDS_FIELD.index = 9
localTable.PLAYERVO_CARDS_FIELD.label = 3
localTable.PLAYERVO_CARDS_FIELD.has_default_value = false
localTable.PLAYERVO_CARDS_FIELD.default_value = {}
localTable.PLAYERVO_CARDS_FIELD.message_type = UNITVO
localTable.PLAYERVO_CARDS_FIELD.type = 11
localTable.PLAYERVO_CARDS_FIELD.cpp_type = 10

localTable.PLAYERVO_PVECARDS_FIELD.name = "pveCards"
localTable.PLAYERVO_PVECARDS_FIELD.full_name = ".VO.PlayerVO.pveCards"
localTable.PLAYERVO_PVECARDS_FIELD.number = 22
localTable.PLAYERVO_PVECARDS_FIELD.index = 10
localTable.PLAYERVO_PVECARDS_FIELD.label = 3
localTable.PLAYERVO_PVECARDS_FIELD.has_default_value = false
localTable.PLAYERVO_PVECARDS_FIELD.default_value = {}
localTable.PLAYERVO_PVECARDS_FIELD.message_type = FORMATIONVO
localTable.PLAYERVO_PVECARDS_FIELD.type = 11
localTable.PLAYERVO_PVECARDS_FIELD.cpp_type = 10

localTable.PLAYERVO_PVPCARDS_FIELD.name = "pvpCards"
localTable.PLAYERVO_PVPCARDS_FIELD.full_name = ".VO.PlayerVO.pvpCards"
localTable.PLAYERVO_PVPCARDS_FIELD.number = 23
localTable.PLAYERVO_PVPCARDS_FIELD.index = 11
localTable.PLAYERVO_PVPCARDS_FIELD.label = 3
localTable.PLAYERVO_PVPCARDS_FIELD.has_default_value = false
localTable.PLAYERVO_PVPCARDS_FIELD.default_value = {}
localTable.PLAYERVO_PVPCARDS_FIELD.message_type = FORMATIONVO
localTable.PLAYERVO_PVPCARDS_FIELD.type = 11
localTable.PLAYERVO_PVPCARDS_FIELD.cpp_type = 10

localTable.PLAYERVO_LASTLOGINTIME_FIELD.name = "lastLoginTime"
localTable.PLAYERVO_LASTLOGINTIME_FIELD.full_name = ".VO.PlayerVO.lastLoginTime"
localTable.PLAYERVO_LASTLOGINTIME_FIELD.number = 41
localTable.PLAYERVO_LASTLOGINTIME_FIELD.index = 12
localTable.PLAYERVO_LASTLOGINTIME_FIELD.label = 1
localTable.PLAYERVO_LASTLOGINTIME_FIELD.has_default_value = false
localTable.PLAYERVO_LASTLOGINTIME_FIELD.default_value = 0
localTable.PLAYERVO_LASTLOGINTIME_FIELD.type = 5
localTable.PLAYERVO_LASTLOGINTIME_FIELD.cpp_type = 1

localTable.PLAYERVO_LASTLOGOUTTIME_FIELD.name = "lastLogoutTime"
localTable.PLAYERVO_LASTLOGOUTTIME_FIELD.full_name = ".VO.PlayerVO.lastLogoutTime"
localTable.PLAYERVO_LASTLOGOUTTIME_FIELD.number = 42
localTable.PLAYERVO_LASTLOGOUTTIME_FIELD.index = 13
localTable.PLAYERVO_LASTLOGOUTTIME_FIELD.label = 1
localTable.PLAYERVO_LASTLOGOUTTIME_FIELD.has_default_value = false
localTable.PLAYERVO_LASTLOGOUTTIME_FIELD.default_value = 0
localTable.PLAYERVO_LASTLOGOUTTIME_FIELD.type = 5
localTable.PLAYERVO_LASTLOGOUTTIME_FIELD.cpp_type = 1

PLAYERVO.name = "PlayerVO"
PLAYERVO.full_name = ".VO.PlayerVO"
PLAYERVO.nested_types = {}
PLAYERVO.enum_types = {}
PLAYERVO.fields = {localTable.PLAYERVO_ACCOUNTID_FIELD, localTable.PLAYERVO_ACCOUNTNAME_FIELD, localTable.PLAYERVO_PLATFORM_FIELD, localTable.PLAYERVO_PLAYERID_FIELD, localTable.PLAYERVO_PLAYERNAME_FIELD, localTable.PLAYERVO_SEX_FIELD, localTable.PLAYERVO_MONEY_FIELD, localTable.PLAYERVO_CASH_FIELD, localTable.PLAYERVO_ENERGY_FIELD, localTable.PLAYERVO_CARDS_FIELD, localTable.PLAYERVO_PVECARDS_FIELD, localTable.PLAYERVO_PVPCARDS_FIELD, localTable.PLAYERVO_LASTLOGINTIME_FIELD, localTable.PLAYERVO_LASTLOGOUTTIME_FIELD}
PLAYERVO.is_extendable = false
PLAYERVO.extensions = {}
localTable.UNITVO_SN_FIELD.name = "sn"
localTable.UNITVO_SN_FIELD.full_name = ".VO.UnitVO.sn"
localTable.UNITVO_SN_FIELD.number = 1
localTable.UNITVO_SN_FIELD.index = 0
localTable.UNITVO_SN_FIELD.label = 1
localTable.UNITVO_SN_FIELD.has_default_value = false
localTable.UNITVO_SN_FIELD.default_value = ""
localTable.UNITVO_SN_FIELD.type = 9
localTable.UNITVO_SN_FIELD.cpp_type = 9

localTable.UNITVO_ID_FIELD.name = "id"
localTable.UNITVO_ID_FIELD.full_name = ".VO.UnitVO.id"
localTable.UNITVO_ID_FIELD.number = 2
localTable.UNITVO_ID_FIELD.index = 1
localTable.UNITVO_ID_FIELD.label = 1
localTable.UNITVO_ID_FIELD.has_default_value = false
localTable.UNITVO_ID_FIELD.default_value = 0
localTable.UNITVO_ID_FIELD.type = 5
localTable.UNITVO_ID_FIELD.cpp_type = 1

localTable.UNITVO_LEVEL_FIELD.name = "level"
localTable.UNITVO_LEVEL_FIELD.full_name = ".VO.UnitVO.level"
localTable.UNITVO_LEVEL_FIELD.number = 3
localTable.UNITVO_LEVEL_FIELD.index = 2
localTable.UNITVO_LEVEL_FIELD.label = 1
localTable.UNITVO_LEVEL_FIELD.has_default_value = false
localTable.UNITVO_LEVEL_FIELD.default_value = 0
localTable.UNITVO_LEVEL_FIELD.type = 5
localTable.UNITVO_LEVEL_FIELD.cpp_type = 1

localTable.UNITVO_EXP_FIELD.name = "exp"
localTable.UNITVO_EXP_FIELD.full_name = ".VO.UnitVO.exp"
localTable.UNITVO_EXP_FIELD.number = 4
localTable.UNITVO_EXP_FIELD.index = 3
localTable.UNITVO_EXP_FIELD.label = 1
localTable.UNITVO_EXP_FIELD.has_default_value = false
localTable.UNITVO_EXP_FIELD.default_value = 0
localTable.UNITVO_EXP_FIELD.type = 5
localTable.UNITVO_EXP_FIELD.cpp_type = 1

localTable.UNITVO_STAR_FIELD.name = "star"
localTable.UNITVO_STAR_FIELD.full_name = ".VO.UnitVO.star"
localTable.UNITVO_STAR_FIELD.number = 5
localTable.UNITVO_STAR_FIELD.index = 4
localTable.UNITVO_STAR_FIELD.label = 1
localTable.UNITVO_STAR_FIELD.has_default_value = false
localTable.UNITVO_STAR_FIELD.default_value = 0
localTable.UNITVO_STAR_FIELD.type = 5
localTable.UNITVO_STAR_FIELD.cpp_type = 1

localTable.UNITVO_SKILLS_FIELD.name = "skills"
localTable.UNITVO_SKILLS_FIELD.full_name = ".VO.UnitVO.skills"
localTable.UNITVO_SKILLS_FIELD.number = 8
localTable.UNITVO_SKILLS_FIELD.index = 5
localTable.UNITVO_SKILLS_FIELD.label = 3
localTable.UNITVO_SKILLS_FIELD.has_default_value = false
localTable.UNITVO_SKILLS_FIELD.default_value = {}
localTable.UNITVO_SKILLS_FIELD.message_type = SKILLVO
localTable.UNITVO_SKILLS_FIELD.type = 11
localTable.UNITVO_SKILLS_FIELD.cpp_type = 10

localTable.UNITVO_BORNTIME_FIELD.name = "bornTime"
localTable.UNITVO_BORNTIME_FIELD.full_name = ".VO.UnitVO.bornTime"
localTable.UNITVO_BORNTIME_FIELD.number = 10
localTable.UNITVO_BORNTIME_FIELD.index = 6
localTable.UNITVO_BORNTIME_FIELD.label = 1
localTable.UNITVO_BORNTIME_FIELD.has_default_value = false
localTable.UNITVO_BORNTIME_FIELD.default_value = 0
localTable.UNITVO_BORNTIME_FIELD.type = 3
localTable.UNITVO_BORNTIME_FIELD.cpp_type = 2

UNITVO.name = "UnitVO"
UNITVO.full_name = ".VO.UnitVO"
UNITVO.nested_types = {}
UNITVO.enum_types = {}
UNITVO.fields = {localTable.UNITVO_SN_FIELD, localTable.UNITVO_ID_FIELD, localTable.UNITVO_LEVEL_FIELD, localTable.UNITVO_EXP_FIELD, localTable.UNITVO_STAR_FIELD, localTable.UNITVO_SKILLS_FIELD, localTable.UNITVO_BORNTIME_FIELD}
UNITVO.is_extendable = false
UNITVO.extensions = {}
localTable.SKILLVO_ID_FIELD.name = "id"
localTable.SKILLVO_ID_FIELD.full_name = ".VO.SkillVO.id"
localTable.SKILLVO_ID_FIELD.number = 1
localTable.SKILLVO_ID_FIELD.index = 0
localTable.SKILLVO_ID_FIELD.label = 1
localTable.SKILLVO_ID_FIELD.has_default_value = false
localTable.SKILLVO_ID_FIELD.default_value = 0
localTable.SKILLVO_ID_FIELD.type = 5
localTable.SKILLVO_ID_FIELD.cpp_type = 1

localTable.SKILLVO_LEVEL_FIELD.name = "level"
localTable.SKILLVO_LEVEL_FIELD.full_name = ".VO.SkillVO.level"
localTable.SKILLVO_LEVEL_FIELD.number = 2
localTable.SKILLVO_LEVEL_FIELD.index = 1
localTable.SKILLVO_LEVEL_FIELD.label = 1
localTable.SKILLVO_LEVEL_FIELD.has_default_value = false
localTable.SKILLVO_LEVEL_FIELD.default_value = 0
localTable.SKILLVO_LEVEL_FIELD.type = 5
localTable.SKILLVO_LEVEL_FIELD.cpp_type = 1

SKILLVO.name = "SkillVO"
SKILLVO.full_name = ".VO.SkillVO"
SKILLVO.nested_types = {}
SKILLVO.enum_types = {}
SKILLVO.fields = {localTable.SKILLVO_ID_FIELD, localTable.SKILLVO_LEVEL_FIELD}
SKILLVO.is_extendable = false
SKILLVO.extensions = {}
localTable.FORMATIONVO_ID_FIELD.name = "id"
localTable.FORMATIONVO_ID_FIELD.full_name = ".VO.FormationVO.id"
localTable.FORMATIONVO_ID_FIELD.number = 1
localTable.FORMATIONVO_ID_FIELD.index = 0
localTable.FORMATIONVO_ID_FIELD.label = 1
localTable.FORMATIONVO_ID_FIELD.has_default_value = false
localTable.FORMATIONVO_ID_FIELD.default_value = 0
localTable.FORMATIONVO_ID_FIELD.type = 5
localTable.FORMATIONVO_ID_FIELD.cpp_type = 1

localTable.FORMATIONVO_ISALTERNATE_FIELD.name = "isAlternate"
localTable.FORMATIONVO_ISALTERNATE_FIELD.full_name = ".VO.FormationVO.isAlternate"
localTable.FORMATIONVO_ISALTERNATE_FIELD.number = 2
localTable.FORMATIONVO_ISALTERNATE_FIELD.index = 1
localTable.FORMATIONVO_ISALTERNATE_FIELD.label = 1
localTable.FORMATIONVO_ISALTERNATE_FIELD.has_default_value = false
localTable.FORMATIONVO_ISALTERNATE_FIELD.default_value = false
localTable.FORMATIONVO_ISALTERNATE_FIELD.type = 8
localTable.FORMATIONVO_ISALTERNATE_FIELD.cpp_type = 7

FORMATIONVO.name = "FormationVO"
FORMATIONVO.full_name = ".VO.FormationVO"
FORMATIONVO.nested_types = {}
FORMATIONVO.enum_types = {}
FORMATIONVO.fields = {localTable.FORMATIONVO_ID_FIELD, localTable.FORMATIONVO_ISALTERNATE_FIELD}
FORMATIONVO.is_extendable = false
FORMATIONVO.extensions = {}
localTable.BATTLEINFOVO_SECTION_FIELD.name = "section"
localTable.BATTLEINFOVO_SECTION_FIELD.full_name = ".VO.BattleInfoVO.section"
localTable.BATTLEINFOVO_SECTION_FIELD.number = 1
localTable.BATTLEINFOVO_SECTION_FIELD.index = 0
localTable.BATTLEINFOVO_SECTION_FIELD.label = 1
localTable.BATTLEINFOVO_SECTION_FIELD.has_default_value = false
localTable.BATTLEINFOVO_SECTION_FIELD.default_value = 0
localTable.BATTLEINFOVO_SECTION_FIELD.type = 5
localTable.BATTLEINFOVO_SECTION_FIELD.cpp_type = 1

localTable.BATTLEINFOVO_FRAME_FIELD.name = "frame"
localTable.BATTLEINFOVO_FRAME_FIELD.full_name = ".VO.BattleInfoVO.frame"
localTable.BATTLEINFOVO_FRAME_FIELD.number = 2
localTable.BATTLEINFOVO_FRAME_FIELD.index = 1
localTable.BATTLEINFOVO_FRAME_FIELD.label = 1
localTable.BATTLEINFOVO_FRAME_FIELD.has_default_value = false
localTable.BATTLEINFOVO_FRAME_FIELD.default_value = 0
localTable.BATTLEINFOVO_FRAME_FIELD.type = 5
localTable.BATTLEINFOVO_FRAME_FIELD.cpp_type = 1

localTable.BATTLEINFOVO_TYPE_FIELD.name = "type"
localTable.BATTLEINFOVO_TYPE_FIELD.full_name = ".VO.BattleInfoVO.type"
localTable.BATTLEINFOVO_TYPE_FIELD.number = 3
localTable.BATTLEINFOVO_TYPE_FIELD.index = 2
localTable.BATTLEINFOVO_TYPE_FIELD.label = 1
localTable.BATTLEINFOVO_TYPE_FIELD.has_default_value = false
localTable.BATTLEINFOVO_TYPE_FIELD.default_value = 0
localTable.BATTLEINFOVO_TYPE_FIELD.type = 5
localTable.BATTLEINFOVO_TYPE_FIELD.cpp_type = 1

localTable.BATTLEINFOVO_PARAM_FIELD.name = "param"
localTable.BATTLEINFOVO_PARAM_FIELD.full_name = ".VO.BattleInfoVO.param"
localTable.BATTLEINFOVO_PARAM_FIELD.number = 4
localTable.BATTLEINFOVO_PARAM_FIELD.index = 3
localTable.BATTLEINFOVO_PARAM_FIELD.label = 1
localTable.BATTLEINFOVO_PARAM_FIELD.has_default_value = false
localTable.BATTLEINFOVO_PARAM_FIELD.default_value = ""
localTable.BATTLEINFOVO_PARAM_FIELD.type = 9
localTable.BATTLEINFOVO_PARAM_FIELD.cpp_type = 9

BATTLEINFOVO.name = "BattleInfoVO"
BATTLEINFOVO.full_name = ".VO.BattleInfoVO"
BATTLEINFOVO.nested_types = {}
BATTLEINFOVO.enum_types = {}
BATTLEINFOVO.fields = {localTable.BATTLEINFOVO_SECTION_FIELD, localTable.BATTLEINFOVO_FRAME_FIELD, localTable.BATTLEINFOVO_TYPE_FIELD, localTable.BATTLEINFOVO_PARAM_FIELD}
BATTLEINFOVO.is_extendable = false
BATTLEINFOVO.extensions = {}

-- accountId, accountName, password, deviceIId, platform, createTime, lastLoginTime, status, banBeginTime, banEndTime, lastLoginIp, 
AccountVO = protobuf.Message(ACCOUNTVO)

-- accountId, accountName, platform, playerId, playerName, sex, money, cash, energy, cards, pveCards, pvpCards, lastLoginTime, lastLogoutTime, 
PlayerVO = protobuf.Message(PLAYERVO)

-- id, isAlternate, 
FormationVO = protobuf.Message(FORMATIONVO)

-- id, level, 
SkillVO = protobuf.Message(SKILLVO)

-- section, frame, type, param, 
BattleInfoVO = protobuf.Message(BATTLEINFOVO)

-- sn, id, level, exp, star, skills, bornTime, 
UnitVO = protobuf.Message(UNITVO)


return m_table