//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ConfigHandlerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ConfigHandler), typeof(System.Object));
		L.RegFunction("OpenFromData", OpenFromData);
		L.RegFunction("Open", Open);
		L.RegFunction("OpenFromStreamingAssets", OpenFromStreamingAssets);
		L.RegFunction("OpenFromMemory", OpenFromMemory);
		L.RegFunction("Clear", Clear);
		L.RegFunction("WriteValue", WriteValue);
		L.RegFunction("ReadValue", ReadValue);
		L.RegFunction("Copy", Copy);
		L.RegFunction("New", _CreateConfigHandler);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateConfigHandler(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ConfigHandler obj = new ConfigHandler();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ConfigHandler.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OpenFromData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ConfigHandler obj = (ConfigHandler)ToLua.CheckObject<ConfigHandler>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.OpenFromData(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Open(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ConfigHandler obj = (ConfigHandler)ToLua.CheckObject<ConfigHandler>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.Open(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OpenFromStreamingAssets(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ConfigHandler obj = (ConfigHandler)ToLua.CheckObject<ConfigHandler>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.OpenFromStreamingAssets(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OpenFromMemory(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				ConfigHandler obj = (ConfigHandler)ToLua.CheckObject<ConfigHandler>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				bool o = obj.OpenFromMemory(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<byte[]>(L, 2))
			{
				ConfigHandler obj = (ConfigHandler)ToLua.CheckObject<ConfigHandler>(L, 1);
				byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
				bool o = obj.OpenFromMemory(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: ConfigHandler.OpenFromMemory");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ConfigHandler obj = (ConfigHandler)ToLua.CheckObject<ConfigHandler>(L, 1);
			obj.Clear();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WriteValue(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			ConfigHandler obj = (ConfigHandler)ToLua.CheckObject<ConfigHandler>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			object arg1 = ToLua.ToVarObject(L, 3);
			obj.WriteValue(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReadValue(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			ConfigHandler obj = (ConfigHandler)ToLua.CheckObject<ConfigHandler>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			object o = obj.ReadValue(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Copy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ConfigHandler obj = (ConfigHandler)ToLua.CheckObject<ConfigHandler>(L, 1);
			ConfigHandler arg0 = (ConfigHandler)ToLua.CheckObject<ConfigHandler>(L, 2);
			obj.Copy(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

